export const courses =[
    "Kinyarwanda",
    "Swahili",
    "English",
    "French",
    "Arts",
    "Sciences",
    "Social Studies",
    "Maths",
    "Physics",
    "Chemistry",
    "Biology",
    "Geography",
    "History",
    "Economics",
    "Literature",
    "Entrepreneurship",
    "Computer science",
    "Other",
]